#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='mypy_extensions',
      version='1.1.0',
      description='Type system extensions for programs checked with the mypy type checker.',
      author=None,
      author_email='The mypy developers <jukka.lehtosalo@iki.fi>',
      url=None,
      py_modules=['mypy_extensions'],
      python_requires='>=3.8',
     )
